apiVersion: v1 
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector: backend
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
    nodePort: {{ .Values.backend.service.port }}