frontend:
  replicas: 1
  image: 
    repository: "git.sethsamuel.online/fluffy/mr_lvl5_m4_front_k8s"
    dockerTag: "latest"
    pullPolicy: "Always"
  service:
    url: mr-lvl5-m4.sethsamuel.online
    type: ClusterIP
    port: 80

backend:
  replicas: 1
  image: 
    repository: "git.sethsamuel.online/fluffy/mr_lvl5_m4_back"
    dockerTag: "latest"
    pullPolicy: "Always"
  service:
    url: backm4.fluffyb.net
    type: ClusterIP
    port: 8000
  # Add this value during helm install with --set backend.geminiApiKey=your-api-key
  geminiApiKey: ""